### ISSUE TITLE
[question]: Any interest on pulling in some of my patches?

### ISSUE THREAD

**Issue by erran** [lassebunk/dish#2]
- [ ] Convert camel case keys into underscore keys. (This is useful in the library I wrote, it's a matter of opinion if it's a good default though)
- [x] Adds support for `#key_name=` methods. (This modified the original has ATM)
- [x] Displays the keys in `#methods` (underscored like about, but could be changed).
- [x] Fixes `#to_json` which is useful when marshaling and unmarshaling to/from HTTP responses.
- [x] Use `#to_h` instead of `#as_hash` (provide an alias for compat.)

---

See the original file used in an API client [here](https://github.com/erran/controlsinsight.rb/blob/master/lib/controls/ext/dish/plate.rb).

**Comment by erran** [comment]
I'd label this as question if I could. Opted to prepend `[question]:` since I couldn't.

**Comment by erran** [comment]
[Here's a gist (lib/dish/plate.rb)](https://gist.github.com/erran/9100613#file-dish-plate-rb).

**Comment by lassebunk** [comment]
Yes, thanks. Could you submit a pull request including tests?
Thanks :)

**Comment by erran** [comment]
Any specific changes you want to pull in? I'll create a PR with just the key changes (setting keys and adding them to `#methods`).

**Comment by lassebunk** [comment]
Thanks. I'm closing this one so we can discuss it on the pull requests.
We also need to talk about the key casing feature. This is really a good idea that I could use myself.
