### ISSUE TITLE
Make Dish::Plate#initialize default the hash

### ISSUE THREAD

**Issue by bobbytables** [lassebunk/dish#3]
When attempting to use Dish with ActiveModel::Model includes it fails because initialize requires the first parameter as a hash, I feel it should be defaulted to `hash = {}`.

Code: https://github.com/lassebunk/dish/blob/master/lib/dish/plate.rb#L13

**Comment by lassebunk** [comment]
Could you provide an example? Thanks.

**Comment by lassebunk** [comment]
@bobbytables ping? :)

**Comment by lassebunk** [comment]
I'm closing this. Please update and reopen if needed.
