### ISSUE TITLE
[question]: Convert CamelCaseKeys to lower_and_snake_case

### ISSUE THREAD

**Issue by erran** [lassebunk/dish#8]
What everyone's opinion on this? User configurable, default option, etc.?

**Comment by lassebunk** [comment]
User configurable. :)

``` ruby
Dish.configure do |config|
  config.key_case = :camel_case # default is :keep
end
```

**Comment by erran** [comment]
I like it. What should the behavior be when there is a bad type provided? Should we create error classes to raise (I rose a `RuntimeError` in one of the other PRs since there are no `Dish::Error`s yet.)

**Comment by lassebunk** [comment]
Nice.
I think it should raise `ArgumentError` right now.

**Comment by lassebunk** [comment]
Should we begin working on this? :)
